version: '3'
volumes:
  data:
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - '53306:3306'
